plugins {
    id "application"
    id "org.jetbrains.kotlin.jvm" version "2.4.20"
    id "org.openjfx.javafxplugin" version "0.1.0"
}

ext {
    appTitle = "reviso"
    appTarget = "25"
    appVersion = "2.2.10"
}

allprojects {
    group = appTitle
    version = appVersion
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.github.ajalt.clikt:clikt:5.1.0"
    implementation "net.pearx.kasechange:kasechange-jvm:1.4.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.4.20"
}

tasks.register('setup', Exec) {
    def destination = layout.buildDirectory.dir("wrapper").get().asFile

    inputs.file "src/main/rust/${appTitle}.rs"
    outputs.dir destination

    commandLine "rustc", "src/main/rust/${appTitle}.rs", "--out-dir", destination, "-C", "opt-level=3"

    doFirst {
        destination.mkdirs()
    }
}

application {
    mainModule = "${appTitle}"
    mainClass = "${appTitle}.Main"
}

distributions {
    main {
        contents {
            from(tasks.named('setup')) {
                into "bin"
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(appTarget)
    }
}

jar {
    manifest {
        attributes "Implementation-Title": appTitle
        attributes "Implementation-Version": appVersion
    }
}

java {
    targetCompatibility = "${appTarget}"
}

javafx {
    version = "27"
    modules = [
        "javafx.base",
        "javafx.controls",
        "javafx.fxml",
        "javafx.graphics",
    ]
}

startScripts {
    enabled = false
}
